### ISSUE TITLE
support react-native 0.60+ auto link?

### ISSUE THREAD

**Issue by vinurs** [react-native-community/react-native-picker#13]
now react-native version has been 0.60.4, and it needs autolink

**Comment by dg92** [comment]
@vinurs what is the error you are seeing?

**Comment by vinurs** [comment]
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - @react-native-community/picker (to unlink run: "react-native unlink @react-native-community/picker")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

**Comment by bartolkaruza** [comment]
@vinurs did you try unlinking and the error is still there?

**Comment by vinurs** [comment]
@bartolkaruza i tried in 0.60.4 again, and without do react-native link, it works well, so the document need update? when u use 0.60+ u needn't do 
```
react-native link @react-native-community/picker
```

**Comment by fattomhk** [comment]
I found `[!] No podspec found for 'react-native-picker' in '../node_modules/@react-native-community/picker'` when doing pod install
Then I changed the name of react-native-camera.podspec to react-native-picker.podspec
and added a homepage to package.json,  it work

**Comment by fattomhk** [comment]
But it shows duplicate symbol
```
duplicate symbol _OBJC_IVAR_$_RCTPicker._selectedIndex in:
    /ios/build/PROJECT/Build/Products/Debug-iphonesimulator/React-Core/libReact-Core.a(RCTPicker.o)
    /ios/build/PROJECT/Build/Products/Debug-iphonesimulator/react-native-picker/libreact-native-picker.a(RCTPicker.o)
```

**Comment by chakrihacker** [comment]
Closing as it's fixed, If you are facing issues feel free to comment

**Comment by schumannd** [comment]
the README should be updated to reflect that running `react-native link` is not necessary anymore for RN 0.60+
